/*
 * Main public include file
 */
#ifndef __KINESIS_VIDEO_WEBRTC_CLIENT_ERROR__
#define __KINESIS_VIDEO_WEBRTC_CLIENT_ERROR__

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#ifndef STATUS
#define STATUS UINT32
#endif

#define STATUS_SUCCESS      ((STATUS) 0x00000000)
#define STATUS_FAILED(x)    (((STATUS)(x)) != STATUS_SUCCESS)
#define STATUS_SUCCEEDED(x) (!STATUS_FAILED(x))

#define STATUS_BASE                              0x00000000
#define STATUS_NULL_ARG                          STATUS_BASE + 0x00000001
#define STATUS_INVALID_ARG                       STATUS_BASE + 0x00000002
#define STATUS_INVALID_ARG_LEN                   STATUS_BASE + 0x00000003
#define STATUS_NOT_ENOUGH_MEMORY                 STATUS_BASE + 0x00000004
#define STATUS_BUFFER_TOO_SMALL                  STATUS_BASE + 0x00000005
#define STATUS_UNEXPECTED_EOF                    STATUS_BASE + 0x00000006
#define STATUS_FORMAT_ERROR                      STATUS_BASE + 0x00000007
#define STATUS_INVALID_HANDLE_ERROR              STATUS_BASE + 0x00000008
#define STATUS_OPEN_FILE_FAILED                  STATUS_BASE + 0x00000009
#define STATUS_READ_FILE_FAILED                  STATUS_BASE + 0x0000000a
#define STATUS_WRITE_TO_FILE_FAILED              STATUS_BASE + 0x0000000b
#define STATUS_INTERNAL_ERROR                    STATUS_BASE + 0x0000000c
#define STATUS_INVALID_OPERATION                 STATUS_BASE + 0x0000000d
#define STATUS_NOT_IMPLEMENTED                   STATUS_BASE + 0x0000000e
#define STATUS_OPERATION_TIMED_OUT               STATUS_BASE + 0x0000000f
#define STATUS_NOT_FOUND                         STATUS_BASE + 0x00000010
#define STATUS_CREATE_THREAD_FAILED              STATUS_BASE + 0x00000011
#define STATUS_THREAD_NOT_ENOUGH_RESOURCES       STATUS_BASE + 0x00000012
#define STATUS_THREAD_INVALID_ARG                STATUS_BASE + 0x00000013
#define STATUS_THREAD_PERMISSIONS                STATUS_BASE + 0x00000014
#define STATUS_THREAD_DEADLOCKED                 STATUS_BASE + 0x00000015
#define STATUS_THREAD_DOES_NOT_EXIST             STATUS_BASE + 0x00000016
#define STATUS_JOIN_THREAD_FAILED                STATUS_BASE + 0x00000017
#define STATUS_WAIT_FAILED                       STATUS_BASE + 0x00000018
#define STATUS_CANCEL_THREAD_FAILED              STATUS_BASE + 0x00000019
#define STATUS_THREAD_IS_NOT_JOINABLE            STATUS_BASE + 0x0000001a
#define STATUS_DETACH_THREAD_FAILED              STATUS_BASE + 0x0000001b
#define STATUS_THREAD_ATTR_INIT_FAILED           STATUS_BASE + 0x0000001c
#define STATUS_THREAD_ATTR_SET_STACK_SIZE_FAILED STATUS_BASE + 0x0000001d
#define STATUS_MEMORY_NOT_FREED                  STATUS_BASE + 0x0000001e

// This section is done for backward compat. We shouldn't add to it. New status should be added to common base section
#define STATUS_COMMON_PRODUCER_BASE                         0x15000000
#define STATUS_INVALID_AWS_CREDENTIALS_VERSION              STATUS_COMMON_PRODUCER_BASE + 0x00000008
#define STATUS_MAX_REQUEST_HEADER_COUNT                     STATUS_COMMON_PRODUCER_BASE + 0x00000009
#define STATUS_MAX_REQUEST_HEADER_NAME_LEN                  STATUS_COMMON_PRODUCER_BASE + 0x0000000a
#define STATUS_MAX_REQUEST_HEADER_VALUE_LEN                 STATUS_COMMON_PRODUCER_BASE + 0x0000000b
#define STATUS_INVALID_API_CALL_RETURN_JSON                 STATUS_COMMON_PRODUCER_BASE + 0x0000000c
#define STATUS_CURL_INIT_FAILED                             STATUS_COMMON_PRODUCER_BASE + 0x0000000d
#define STATUS_CURL_LIBRARY_INIT_FAILED                     STATUS_COMMON_PRODUCER_BASE + 0x0000000e
#define STATUS_HMAC_GENERATION_ERROR                        STATUS_COMMON_PRODUCER_BASE + 0x00000010
#define STATUS_IOT_FAILED                                   STATUS_COMMON_PRODUCER_BASE + 0x00000011
#define STATUS_MAX_ROLE_ALIAS_LEN_EXCEEDED                  STATUS_COMMON_PRODUCER_BASE + 0x00000012
#define STATUS_INVALID_USER_AGENT_LENGTH                    STATUS_COMMON_PRODUCER_BASE + 0x00000015
#define STATUS_IOT_EXPIRATION_OCCURS_IN_PAST                STATUS_COMMON_PRODUCER_BASE + 0x00000017
#define STATUS_IOT_EXPIRATION_PARSING_FAILED                STATUS_COMMON_PRODUCER_BASE + 0x00000018
#define STATUS_MAX_IOT_THING_NAME_LENGTH                    STATUS_COMMON_PRODUCER_BASE + 0x0000001e
#define STATUS_IOT_CREATE_LWS_CONTEXT_FAILED                STATUS_COMMON_PRODUCER_BASE + 0x0000001f
#define STATUS_INVALID_CA_CERT_PATH                         STATUS_COMMON_PRODUCER_BASE + 0x00000020
#define STATUS_FILE_CREDENTIAL_PROVIDER_OPEN_FILE_FAILED    STATUS_COMMON_PRODUCER_BASE + 0x00000022
#define STATUS_FILE_CREDENTIAL_PROVIDER_INVALID_FILE_LENGTH STATUS_COMMON_PRODUCER_BASE + 0x00000023
#define STATUS_FILE_CREDENTIAL_PROVIDER_INVALID_FILE_FORMAT STATUS_COMMON_PRODUCER_BASE + 0x00000024

// Continue errors from the new common base
#define STATUS_COMMON_BASE 0x16000000

#define STATUS_MKVGEN_BASE                                  0x32000000
#define STATUS_MKV_INVALID_FRAME_DATA                       STATUS_MKVGEN_BASE + 0x00000001
#define STATUS_MKV_INVALID_FRAME_TIMESTAMP                  STATUS_MKVGEN_BASE + 0x00000002
#define STATUS_MKV_INVALID_CLUSTER_DURATION                 STATUS_MKVGEN_BASE + 0x00000003
#define STATUS_MKV_INVALID_CONTENT_TYPE_LENGTH              STATUS_MKVGEN_BASE + 0x00000004
#define STATUS_MKV_NUMBER_TOO_BIG                           STATUS_MKVGEN_BASE + 0x00000005
#define STATUS_MKV_INVALID_CODEC_ID_LENGTH                  STATUS_MKVGEN_BASE + 0x00000006
#define STATUS_MKV_INVALID_TRACK_NAME_LENGTH                STATUS_MKVGEN_BASE + 0x00000007
#define STATUS_MKV_INVALID_CODEC_PRIVATE_LENGTH             STATUS_MKVGEN_BASE + 0x00000008
#define STATUS_MKV_CODEC_PRIVATE_NULL                       STATUS_MKVGEN_BASE + 0x00000009
#define STATUS_MKV_INVALID_TIMECODE_SCALE                   STATUS_MKVGEN_BASE + 0x0000000a
#define STATUS_MKV_MAX_FRAME_TIMECODE                       STATUS_MKVGEN_BASE + 0x0000000b
#define STATUS_MKV_LARGE_FRAME_TIMECODE                     STATUS_MKVGEN_BASE + 0x0000000c
#define STATUS_MKV_INVALID_ANNEXB_NALU_IN_FRAME_DATA        STATUS_MKVGEN_BASE + 0x0000000d
#define STATUS_MKV_INVALID_AVCC_NALU_IN_FRAME_DATA          STATUS_MKVGEN_BASE + 0x0000000e
#define STATUS_MKV_BOTH_ANNEXB_AND_AVCC_SPECIFIED           STATUS_MKVGEN_BASE + 0x0000000f
#define STATUS_MKV_INVALID_ANNEXB_NALU_IN_CPD               STATUS_MKVGEN_BASE + 0x00000010
#define STATUS_MKV_PTS_DTS_ARE_NOT_SAME                     STATUS_MKVGEN_BASE + 0x00000011
#define STATUS_MKV_INVALID_H264_H265_CPD                    STATUS_MKVGEN_BASE + 0x00000012
#define STATUS_MKV_INVALID_H264_H265_SPS_WIDTH              STATUS_MKVGEN_BASE + 0x00000013
#define STATUS_MKV_INVALID_H264_H265_SPS_HEIGHT             STATUS_MKVGEN_BASE + 0x00000014
#define STATUS_MKV_INVALID_H264_H265_SPS_NALU               STATUS_MKVGEN_BASE + 0x00000015
#define STATUS_MKV_INVALID_BIH_CPD                          STATUS_MKVGEN_BASE + 0x00000016
#define STATUS_MKV_INVALID_HEVC_NALU_COUNT                  STATUS_MKVGEN_BASE + 0x00000017
#define STATUS_MKV_INVALID_HEVC_FORMAT                      STATUS_MKVGEN_BASE + 0x00000018
#define STATUS_MKV_HEVC_SPS_NALU_MISSING                    STATUS_MKVGEN_BASE + 0x00000019
#define STATUS_MKV_INVALID_HEVC_SPS_NALU_SIZE               STATUS_MKVGEN_BASE + 0x0000001a
#define STATUS_MKV_INVALID_HEVC_SPS_CHROMA_FORMAT_IDC       STATUS_MKVGEN_BASE + 0x0000001b
#define STATUS_MKV_INVALID_HEVC_SPS_RESERVED                STATUS_MKVGEN_BASE + 0x0000001c
#define STATUS_MKV_MIN_ANNEX_B_CPD_SIZE                     STATUS_MKVGEN_BASE + 0x0000001d
#define STATUS_MKV_ANNEXB_CPD_MISSING_NALUS                 STATUS_MKVGEN_BASE + 0x0000001e
#define STATUS_MKV_INVALID_ANNEXB_CPD_NALUS                 STATUS_MKVGEN_BASE + 0x0000001f
#define STATUS_MKV_INVALID_TAG_NAME_LENGTH                  STATUS_MKVGEN_BASE + 0x00000020
#define STATUS_MKV_INVALID_TAG_VALUE_LENGTH                 STATUS_MKVGEN_BASE + 0x00000021
#define STATUS_MKV_INVALID_GENERATOR_STATE_TAGS             STATUS_MKVGEN_BASE + 0x00000022
#define STATUS_MKV_INVALID_AAC_CPD_SAMPLING_FREQUENCY_INDEX STATUS_MKVGEN_BASE + 0x00000023
#define STATUS_MKV_INVALID_AAC_CPD_CHANNEL_CONFIG           STATUS_MKVGEN_BASE + 0x00000024
#define STATUS_MKV_INVALID_AAC_CPD                          STATUS_MKVGEN_BASE + 0x00000025
#define STATUS_MKV_TRACK_INFO_NOT_FOUND                     STATUS_MKVGEN_BASE + 0x00000026
#define STATUS_MKV_INVALID_SEGMENT_UUID                     STATUS_MKVGEN_BASE + 0x00000027
#define STATUS_MKV_INVALID_TRACK_UID                        STATUS_MKVGEN_BASE + 0x00000028
#define STATUS_MKV_INVALID_CLIENT_ID_LENGTH                 STATUS_MKVGEN_BASE + 0x00000029
#define STATUS_MKV_INVALID_AMS_ACM_CPD                      STATUS_MKVGEN_BASE + 0x0000002a
#define STATUS_MKV_MISSING_SPS_FROM_H264_CPD                STATUS_MKVGEN_BASE + 0x0000002b
#define STATUS_MKV_MISSING_PPS_FROM_H264_CPD                STATUS_MKVGEN_BASE + 0x0000002c

/**
 * Error values
 */
#define STATUS_UTILS_BASE                            0x40000000
#define STATUS_INVALID_BASE64_ENCODE                 STATUS_UTILS_BASE + 0x00000001
#define STATUS_INVALID_BASE                          STATUS_UTILS_BASE + 0x00000002
#define STATUS_INVALID_DIGIT                         STATUS_UTILS_BASE + 0x00000003
#define STATUS_INT_OVERFLOW                          STATUS_UTILS_BASE + 0x00000004
#define STATUS_EMPTY_STRING                          STATUS_UTILS_BASE + 0x00000005
#define STATUS_DIRECTORY_OPEN_FAILED                 STATUS_UTILS_BASE + 0x00000006
#define STATUS_PATH_TOO_LONG                         STATUS_UTILS_BASE + 0x00000007
#define STATUS_UNKNOWN_DIR_ENTRY_TYPE                STATUS_UTILS_BASE + 0x00000008
#define STATUS_REMOVE_DIRECTORY_FAILED               STATUS_UTILS_BASE + 0x00000009
#define STATUS_REMOVE_FILE_FAILED                    STATUS_UTILS_BASE + 0x0000000a
#define STATUS_REMOVE_LINK_FAILED                    STATUS_UTILS_BASE + 0x0000000b
#define STATUS_DIRECTORY_ACCESS_DENIED               STATUS_UTILS_BASE + 0x0000000c
#define STATUS_DIRECTORY_MISSING_PATH                STATUS_UTILS_BASE + 0x0000000d
#define STATUS_DIRECTORY_ENTRY_STAT_ERROR            STATUS_UTILS_BASE + 0x0000000e
#define STATUS_STRFTIME_FALIED                       STATUS_UTILS_BASE + 0x0000000f
#define STATUS_MAX_TIMESTAMP_FORMAT_STR_LEN_EXCEEDED STATUS_UTILS_BASE + 0x00000010
#define STATUS_UTIL_MAX_TAG_COUNT                    STATUS_UTILS_BASE + 0x00000011
#define STATUS_UTIL_INVALID_TAG_VERSION              STATUS_UTILS_BASE + 0x00000012
#define STATUS_UTIL_TAGS_COUNT_NON_ZERO_TAGS_NULL    STATUS_UTILS_BASE + 0x00000013
#define STATUS_UTIL_INVALID_TAG_NAME_LEN             STATUS_UTILS_BASE + 0x00000014
#define STATUS_UTIL_INVALID_TAG_VALUE_LEN            STATUS_UTILS_BASE + 0x00000015
/**
 * Hash table error values starting from 0x40100000
 */
#define STATUS_HASH_TABLE_BASE            STATUS_UTILS_BASE + 0x00100000
#define STATUS_HASH_KEY_NOT_PRESENT       STATUS_HASH_TABLE_BASE + 0x00000001
#define STATUS_HASH_KEY_ALREADY_PRESENT   STATUS_HASH_TABLE_BASE + 0x00000002
#define STATUS_HASH_ENTRY_ITERATION_ABORT STATUS_HASH_TABLE_BASE + 0x00000003
/**
 * Bit reader error values starting from 0x41000000
 */
#define STATUS_BIT_READER_BASE         STATUS_UTILS_BASE + 0x01000000
#define STATUS_BIT_READER_OUT_OF_RANGE STATUS_BIT_READER_BASE + 0x00000001
#define STATUS_BIT_READER_INVALID_SIZE STATUS_BIT_READER_BASE + 0x00000002
/**
 * Timer queue error values starting from 0x41100000
 */
#define STATUS_TIMER_QUEUE_BASE            STATUS_UTILS_BASE + 0x01100000
#define STATUS_TIMER_QUEUE_STOP_SCHEDULING STATUS_TIMER_QUEUE_BASE + 0x00000001
#define STATUS_INVALID_TIMER_COUNT_VALUE   STATUS_TIMER_QUEUE_BASE + 0x00000002
#define STATUS_INVALID_TIMER_PERIOD_VALUE  STATUS_TIMER_QUEUE_BASE + 0x00000003
#define STATUS_MAX_TIMER_COUNT_REACHED     STATUS_TIMER_QUEUE_BASE + 0x00000004
/**
 * Semaphore error values starting from 0x41200000
 */
#define STATUS_SEMAPHORE_BASE                     STATUS_UTILS_BASE + 0x01200000
#define STATUS_SEMAPHORE_OPERATION_AFTER_SHUTDOWN STATUS_SEMAPHORE_BASE + 0x00000001
#define STATUS_SEMAPHORE_ACQUIRE_WHEN_LOCKED      STATUS_SEMAPHORE_BASE + 0x00000002
/**
 * File logger error values starting from 0x41300000
 */
#define STATUS_FILE_LOGGER_BASE                    STATUS_UTILS_BASE + 0x01200000
#define STATUS_FILE_LOGGER_INDEX_FILE_INVALID_SIZE STATUS_SEMAPHORE_BASE + 0x00000001

#define STATUS_CLIENT_BASE                       0x52000000
#define STATUS_SERVICE_CALL_NOT_AUTHORIZED_ERROR STATUS_CLIENT_BASE + 0x00000010
#define STATUS_INVALID_AUTH_LEN                  STATUS_CLIENT_BASE + 0x00000018
#define STATUS_SERVICE_CALL_TIMEOUT_ERROR        STATUS_CLIENT_BASE + 0x00000037

#define STATUS_STATE_BASE                    0x52000000
#define STATUS_INVALID_STREAM_STATE          STATUS_STATE_BASE + 0x0000000e
#define STATUS_STATE_MACHINE_STATE_NOT_FOUND STATUS_STATE_BASE + 0x00000056

/////////////////////////////////////////////////////
/// Session description init related status codes
/////////////////////////////////////////////////////
/*! \addtogroup SessionDescriptionInitStatusCodes
 * WEBRTC Session Description initialization related codes. Values are derived
 * from STATUS_WEBRTC_BASE (0x55000000)
 *  @{
 */
#define STATUS_WEBRTC_BASE                                         0x55000000
#define STATUS_SESSION_DESCRIPTION_INIT_NOT_OBJECT                 STATUS_WEBRTC_BASE + 0x00000001
#define STATUS_SESSION_DESCRIPTION_INIT_MISSING_SDP_OR_TYPE_MEMBER STATUS_WEBRTC_BASE + 0x00000002
#define STATUS_SESSION_DESCRIPTION_INIT_INVALID_TYPE               STATUS_WEBRTC_BASE + 0x00000003
#define STATUS_SESSION_DESCRIPTION_INIT_MISSING_SDP                STATUS_WEBRTC_BASE + 0x00000004
#define STATUS_SESSION_DESCRIPTION_INIT_MISSING_TYPE               STATUS_WEBRTC_BASE + 0x00000005
#define STATUS_SESSION_DESCRIPTION_INIT_MAX_SDP_LEN_EXCEEDED       STATUS_WEBRTC_BASE + 0x00000006
#define STATUS_SESSION_DESCRIPTION_INVALID_SESSION_DESCRIPTION     STATUS_WEBRTC_BASE + 0x00000007
#define STATUS_SESSION_DESCRIPTION_MISSING_ICE_VALUES              STATUS_WEBRTC_BASE + 0x00000008
#define STATUS_SESSION_DESCRIPTION_MISSING_CERTIFICATE_FINGERPRINT STATUS_WEBRTC_BASE + 0x00000009
#define STATUS_SESSION_DESCRIPTION_MAX_MEDIA_COUNT                 STATUS_WEBRTC_BASE + 0x0000000A
/*!@} */

/////////////////////////////////////////////////////
/// SDP related status codes
/////////////////////////////////////////////////////
/*! \addtogroup SDPStatusCodes
 * WEBRTC SDP packet related codes. Values are derived from STATUS_SDP_BASE
 * (0x56000000)
 *  @{
 */
#define STATUS_SDP_BASE                         STATUS_WEBRTC_BASE + 0x01000000
#define STATUS_SDP_MISSING_ITEMS                STATUS_SDP_BASE + 0x00000001
#define STATUS_SDP_ATTRIBUTES_ERROR             STATUS_SDP_BASE + 0x00000002
#define STATUS_SDP_BANDWIDTH_ERROR              STATUS_SDP_BASE + 0x00000003
#define STATUS_SDP_CONNECTION_INFORMATION_ERROR STATUS_SDP_BASE + 0x00000004
#define STATUS_SDP_EMAIL_ADDRESS_ERROR          STATUS_SDP_BASE + 0x00000005
#define STATUS_SDP_ENCYRPTION_KEY_ERROR         STATUS_SDP_BASE + 0x00000006
#define STATUS_SDP_INFORMATION_ERROR            STATUS_SDP_BASE + 0x00000007
#define STATUS_SDP_MEDIA_NAME_ERROR             STATUS_SDP_BASE + 0x00000008
#define STATUS_SDP_ORIGIN_ERROR                 STATUS_SDP_BASE + 0x00000009
#define STATUS_SDP_PHONE_NUMBER_ERROR           STATUS_SDP_BASE + 0x0000000A
#define STATUS_SDP_TIME_DECRYPTION_ERROR        STATUS_SDP_BASE + 0x0000000B
#define STATUS_SDP_TIMEZONE_ERROR               STATUS_SDP_BASE + 0x0000000C
#define STATUS_SDP_URI_ERROR                    STATUS_SDP_BASE + 0x0000000D
#define STATUS_SDP_VERSION_ERROR                STATUS_SDP_BASE + 0x0000000E
#define STATUS_SDP_ATTRIBUTE_MAX_EXCEEDED       STATUS_SDP_BASE + 0x0000000F
#define STATUS_SDP_NULL_ARG                     STATUS_SDP_BASE + 0x00000010
#define STATUS_SDP_ICE_CANDIDATE_NULL_ARG       STATUS_SDP_BASE + 0x00000011

/*!@} */

/////////////////////////////////////////////////////
/// STUN related status codes
/////////////////////////////////////////////////////

/*! \addtogroup STUNStatusCodes
 * WEBRTC STUN related codes. Values are derived from STATUS_STUN_BASE (0x57000000)
 *  @{
 */
#define STATUS_STUN_BASE                                           STATUS_SDP_BASE + 0x01000000
#define STATUS_STUN_MESSAGE_INTEGRITY_NOT_LAST                     STATUS_STUN_BASE + 0x00000001
#define STATUS_STUN_MESSAGE_INTEGRITY_SIZE_ALIGNMENT               STATUS_STUN_BASE + 0x00000002
#define STATUS_STUN_FINGERPRINT_NOT_LAST                           STATUS_STUN_BASE + 0x00000003
#define STATUS_STUN_MAGIC_COOKIE_MISMATCH                          STATUS_STUN_BASE + 0x00000004
#define STATUS_STUN_INVALID_ADDRESS_ATTRIBUTE_LENGTH               STATUS_STUN_BASE + 0x00000005
#define STATUS_STUN_INVALID_USERNAME_ATTRIBUTE_LENGTH              STATUS_STUN_BASE + 0x00000006
#define STATUS_STUN_INVALID_MESSAGE_INTEGRITY_ATTRIBUTE_LENGTH     STATUS_STUN_BASE + 0x00000007
#define STATUS_STUN_INVALID_FINGERPRINT_ATTRIBUTE_LENGTH           STATUS_STUN_BASE + 0x00000008
#define STATUS_STUN_MULTIPLE_MESSAGE_INTEGRITY_ATTRIBUTES          STATUS_STUN_BASE + 0x00000009
#define STATUS_STUN_MULTIPLE_FINGERPRINT_ATTRIBUTES                STATUS_STUN_BASE + 0x0000000A
#define STATUS_STUN_ATTRIBUTES_AFTER_FINGERPRINT_MESSAGE_INTEGRITY STATUS_STUN_BASE + 0x0000000B
#define STATUS_STUN_MESSAGE_INTEGRITY_AFTER_FINGERPRINT            STATUS_STUN_BASE + 0x0000000C
#define STATUS_STUN_MAX_ATTRIBUTE_COUNT                            STATUS_STUN_BASE + 0x0000000D
#define STATUS_STUN_MESSAGE_INTEGRITY_MISMATCH                     STATUS_STUN_BASE + 0x0000000E
#define STATUS_STUN_FINGERPRINT_MISMATCH                           STATUS_STUN_BASE + 0x0000000F
#define STATUS_STUN_INVALID_PRIORITY_ATTRIBUTE_LENGTH              STATUS_STUN_BASE + 0x00000010
#define STATUS_STUN_INVALID_USE_CANDIDATE_ATTRIBUTE_LENGTH         STATUS_STUN_BASE + 0x00000011
#define STATUS_STUN_INVALID_LIFETIME_ATTRIBUTE_LENGTH              STATUS_STUN_BASE + 0x00000012
#define STATUS_STUN_INVALID_REQUESTED_TRANSPORT_ATTRIBUTE_LENGTH   STATUS_STUN_BASE + 0x00000013
#define STATUS_STUN_INVALID_REALM_ATTRIBUTE_LENGTH                 STATUS_STUN_BASE + 0x00000014
#define STATUS_STUN_INVALID_NONCE_ATTRIBUTE_LENGTH                 STATUS_STUN_BASE + 0x00000015
#define STATUS_STUN_INVALID_ERROR_CODE_ATTRIBUTE_LENGTH            STATUS_STUN_BASE + 0x00000016
#define STATUS_STUN_INVALID_ICE_CONTROL_ATTRIBUTE_LENGTH           STATUS_STUN_BASE + 0x00000017
#define STATUS_STUN_INVALID_CHANNEL_NUMBER_ATTRIBUTE_LENGTH        STATUS_STUN_BASE + 0x00000018
#define STATUS_STUN_INVALID_CHANGE_REQUEST_ATTRIBUTE_LENGTH        STATUS_STUN_BASE + 0x00000019
#define STATUS_STUN_SERIALIZE_EMPTY_STUN_BUF                       STATUS_STUN_BASE + 0x0000001A
#define STATUS_STUN_SERIALIZE_EMPTY_BUF_SIZE                       STATUS_STUN_BASE + 0x0000001B
#define STATUS_STUN_SERIALIZE_INVALID_MSG_INTEGRITY                STATUS_STUN_BASE + 0x0000001C
/*!@} */

/////////////////////////////////////////////////////
/// Networking related status codes
/////////////////////////////////////////////////////

/*! \addtogroup NetworkingStatusCodes
 * WEBRTC Networking related codes. Values are derived from STATUS_NETWORKING_BASE (0x58000000)
 *  @{
 */
#define STATUS_NETWORKING_BASE                     STATUS_STUN_BASE + 0x01000000
#define STATUS_GET_LOCAL_IP_ADDRESSES_FAILED       STATUS_NETWORKING_BASE + 0x00000016
#define STATUS_CREATE_UDP_SOCKET_FAILED            STATUS_NETWORKING_BASE + 0x00000017
#define STATUS_BINDING_SOCKET_FAILED               STATUS_NETWORKING_BASE + 0x00000018
#define STATUS_GET_PORT_NUMBER_FAILED              STATUS_NETWORKING_BASE + 0x00000019
#define STATUS_SEND_DATA_FAILED                    STATUS_NETWORKING_BASE + 0x0000001a
#define STATUS_RESOLVE_HOSTNAME_FAILED             STATUS_NETWORKING_BASE + 0x0000001b
#define STATUS_HOSTNAME_NOT_FOUND                  STATUS_NETWORKING_BASE + 0x0000001c
#define STATUS_SOCKET_CONNECT_FAILED               STATUS_NETWORKING_BASE + 0x0000001d
#define STATUS_CREATE_SSL_FAILED                   STATUS_NETWORKING_BASE + 0x0000001e
#define STATUS_SSL_CONNECTION_FAILED               STATUS_NETWORKING_BASE + 0x0000001f
#define STATUS_SECURE_SOCKET_READ_FAILED           STATUS_NETWORKING_BASE + 0x00000020
#define STATUS_SOCKET_CONNECTION_NOT_READY_TO_SEND STATUS_NETWORKING_BASE + 0x00000021
#define STATUS_SOCKET_CONNECTION_CLOSED_ALREADY    STATUS_NETWORKING_BASE + 0x00000022
#define STATUS_SOCKET_SET_SEND_BUFFER_SIZE_FAILED  STATUS_NETWORKING_BASE + 0x00000023
#define STATUS_GET_SOCKET_FLAG_FAILED              STATUS_NETWORKING_BASE + 0x00000024
#define STATUS_SET_SOCKET_FLAG_FAILED              STATUS_NETWORKING_BASE + 0x00000025
#define STATUS_CLOSE_SOCKET_FAILED                 STATUS_NETWORKING_BASE + 0x00000026
#define STATUS_SOCKET_INVALID_ARG                  STATUS_NETWORKING_BASE + 0x00000027
#define STATUS_RECV_DATA_FAILED                    STATUS_NETWORKING_BASE + 0x00000028
#define STATUS_INIT_NETWORK_FAILED                 STATUS_NETWORKING_BASE + 0x00000029
#define STATUS_NETWORK_CONFIG_ERROR                STATUS_NETWORKING_BASE + 0x0000002A
#define STATUS_NETWORK_SETUP_ERROR                 STATUS_NETWORKING_BASE + 0x0000002B
#define STATUS_NETWORK_SSL_HANDSHAKE_ERROR         STATUS_NETWORKING_BASE + 0x0000002C
#define STATUS_NETWORK_SOCKET_NOT_CONNECTED        STATUS_NETWORKING_BASE + 0x0000002D
#define STATUS_NETWORK_NO_AVAILABLE_RECV_DATA      STATUS_NETWORKING_BASE + 0x0000002E
#define STATUS_NETWORK_SELECT_ERROR                STATUS_NETWORKING_BASE + 0x0000002F

/*!@} */

/////////////////////////////////////////////////////
/// DTLS related status codes
/////////////////////////////////////////////////////

/*! \addtogroup DTLSStatusCodes
 * WEBRTC DTLS related codes. Values are derived from STATUS_DTLS_BASE (0x59000000)
 *  @{
 */
#define STATUS_DTLS_BASE                                  STATUS_NETWORKING_BASE + 0x01000000
#define STATUS_CERTIFICATE_GENERATION_FAILED              STATUS_DTLS_BASE + 0x00000001
#define STATUS_SSL_CTX_CREATION_FAILED                    STATUS_DTLS_BASE + 0x00000002
#define STATUS_SSL_REMOTE_CERTIFICATE_VERIFICATION_FAILED STATUS_DTLS_BASE + 0x00000003
#define STATUS_SSL_PACKET_BEFORE_DTLS_READY               STATUS_DTLS_BASE + 0x00000004
#define STATUS_SSL_UNKNOWN_SRTP_PROFILE                   STATUS_DTLS_BASE + 0x00000005
#define STATUS_SSL_INVALID_CERTIFICATE_BITS               STATUS_DTLS_BASE + 0x00000006
#define STATUS_RSA_CERTIFICATE_GENERATION_FAILED          STATUS_DTLS_BASE + 0x00000007
#define STATUS_ECP_CERTIFICATE_GENERATION_FAILED          STATUS_DTLS_BASE + 0x00000008
#define STATUS_DTLS_NULL_ARG                              STATUS_DTLS_BASE + 0x00000009
#define STATUS_DTLS_DRBG_SEED_FAILED                      STATUS_DTLS_BASE + 0x0000000A
#define STATUS_DTLS_RSA_GEN_KEY_FAILED                    STATUS_DTLS_BASE + 0x0000000B
#define STATUS_DTLS_ECP_GEN_KEY_FAILED                    STATUS_DTLS_BASE + 0x0000000C
#define STATUS_DTLS_MPI_READ_FAILED                       STATUS_DTLS_BASE + 0x0000000D
#define STATUS_DTLS_GEN_TIME_FAILED                       STATUS_DTLS_BASE + 0x0000000E
#define STATUS_DTLS_X509_SET_FAILED                       STATUS_DTLS_BASE + 0x0000000F
#define STATUS_DTLS_SSL_CTX_SETUP_FAILED                  STATUS_DTLS_BASE + 0x00000010
#define STATUS_TLS_SSL_CTX_SETUP_FAILED                   STATUS_DTLS_BASE + 0x00000011
#define STATUS_TLS_SSL_HANDSHAKE_FAILED                   STATUS_DTLS_BASE + 0x00000012
/*!@} */

/////////////////////////////////////////////////////
/// ICE/TURN related status codes
/////////////////////////////////////////////////////

/*! \addtogroup ICEStatusCodes
 * WEBRTC ICE related codes. Values are derived from STATUS_ICE_BASE (0x5a000000)
 *  @{
 */
#define STATUS_ICE_BASE                                                    STATUS_DTLS_BASE + 0x01000000
#define STATUS_ICE_AGENT_NO_SELECTED_CANDIDATE_AVAILABLE                   STATUS_ICE_BASE + 0x00000001
#define STATUS_ICE_CANDIDATE_STRING_MISSING_PORT                           STATUS_ICE_BASE + 0x00000002
#define STATUS_ICE_CANDIDATE_STRING_MISSING_IP                             STATUS_ICE_BASE + 0x00000003
#define STATUS_ICE_CANDIDATE_STRING_INVALID_IP                             STATUS_ICE_BASE + 0x00000004
#define STATUS_ICE_CANDIDATE_STRING_IS_TCP                                 STATUS_ICE_BASE + 0x00000005
#define STATUS_ICE_FAILED_TO_COMPUTE_MD5_FOR_LONG_TERM_CREDENTIAL          STATUS_ICE_BASE + 0x00000006
#define STATUS_ICE_URL_INVALID_PREFIX                                      STATUS_ICE_BASE + 0x00000007
#define STATUS_ICE_URL_TURN_MISSING_USERNAME                               STATUS_ICE_BASE + 0x00000008
#define STATUS_ICE_URL_TURN_MISSING_CREDENTIAL                             STATUS_ICE_BASE + 0x00000009
#define STATUS_ICE_AGENT_STATE_CHANGE_FAILED                               STATUS_ICE_BASE + 0x0000000a
#define STATUS_ICE_NO_LOCAL_CANDIDATE_AVAILABLE_AFTER_GATHERING_TIMEOUT    STATUS_ICE_BASE + 0x0000000b
#define STATUS_ICE_AGENT_TERMINATED_ALREADY                                STATUS_ICE_BASE + 0x0000000c
#define STATUS_ICE_NO_CONNECTED_CANDIDATE_PAIR                             STATUS_ICE_BASE + 0x0000000d
#define STATUS_ICE_CANDIDATE_PAIR_LIST_EMPTY                               STATUS_ICE_BASE + 0x0000000e
#define STATUS_ICE_NOMINATED_CANDIDATE_NOT_CONNECTED                       STATUS_ICE_BASE + 0x00000010
#define STATUS_ICE_CANDIDATE_INIT_MALFORMED                                STATUS_ICE_BASE + 0x00000011
#define STATUS_ICE_CANDIDATE_MISSING_CANDIDATE                             STATUS_ICE_BASE + 0x00000012
#define STATUS_ICE_FAILED_TO_NOMINATE_CANDIDATE_PAIR                       STATUS_ICE_BASE + 0x00000013
#define STATUS_ICE_MAX_REMOTE_CANDIDATE_COUNT_EXCEEDED                     STATUS_ICE_BASE + 0x00000014
#define STATUS_ICE_INVALID_STATE                                           STATUS_ICE_BASE + 0x0000001c
#define STATUS_ICE_NO_LOCAL_HOST_CANDIDATE_AVAILABLE                       STATUS_ICE_BASE + 0x0000001d
#define STATUS_ICE_NO_NOMINATED_VALID_CANDIDATE_PAIR_AVAILABLE             STATUS_ICE_BASE + 0x0000001e
#define STATUS_TURN_CONNECTION_NO_HOST_INTERFACE_FOUND                     STATUS_ICE_BASE + 0x0000001f
#define STATUS_TURN_CONNECTION_STATE_TRANSITION_TIMEOUT                    STATUS_ICE_BASE + 0x00000020
#define STATUS_TURN_CONNECTION_FAILED_TO_CREATE_PERMISSION                 STATUS_ICE_BASE + 0x00000021
#define STATUS_TURN_CONNECTION_FAILED_TO_BIND_CHANNEL                      STATUS_ICE_BASE + 0x00000022
#define STATUS_TURN_NEW_DATA_CHANNEL_MSG_HEADER_BEFORE_PREVIOUS_MSG_FINISH STATUS_ICE_BASE + 0x00000023
#define STATUS_TURN_MISSING_CHANNEL_DATA_HEADER                            STATUS_ICE_BASE + 0x00000024
#define STATUS_ICE_FAILED_TO_RECOVER_FROM_DISCONNECTION                    STATUS_ICE_BASE + 0x00000025
#define STATUS_ICE_NO_AVAILABLE_ICE_CANDIDATE_PAIR                         STATUS_ICE_BASE + 0x00000026
#define STATUS_TURN_CONNECTION_PEER_NOT_USABLE                             STATUS_ICE_BASE + 0x00000027
#define STATUS_ICE_SERVER_INDEX_INVALID                                    STATUS_ICE_BASE + 0x00000028
#define STATUS_ICE_NOT_ENOUGH_MEMORY                                       STATUS_ICE_BASE + 0x00000029
#define STATUS_ICE_NULL_ARG                                                STATUS_ICE_BASE + 0x0000002A
#define STATUS_ICE_NULL_NOMINATED_CANDIDATE_PAIR                           STATUS_ICE_BASE + 0x0000002B
#define STATUS_TURN_CONNECTION_CHECK_CONN_TIMEOUT                          STATUS_ICE_BASE + 0x0000002C
#define STATUS_TURN_CONNECTION_GET_CREDENTIALS_TIMEOUT                     STATUS_ICE_BASE + 0x0000002D
#define STATUS_TURN_CONNECTION_ALLOCATION_TIMEOUT                          STATUS_ICE_BASE + 0x0000002E
#define STATUS_ICE_CANDIDATE_STRING_MISSING_TYPE                           STATUS_ICE_BASE + 0x0000002F
#define STATUS_TURN_CONNECTION_CREATE_SOCKET                               STATUS_ICE_BASE + 0x00000030
#define STATUS_TURN_FSM_REFRESH_ALLOCATION                                 STATUS_ICE_BASE + 0x00000031
#define STATUS_ICE_EMPTY_STUN_SEND_BUF                                     STATUS_ICE_BASE + 0x00000032

/*!@} */

/////////////////////////////////////////////////////
/// SRTP related status codes
/////////////////////////////////////////////////////

/*! \addtogroup SRTPStatusCodes
 * WEBRTC SRTP related codes. Values are derived from STATUS_SRTP_BASE (0x5b000000)
 *  @{
 */
#define STATUS_SRTP_BASE                             STATUS_ICE_BASE + 0x01000000
#define STATUS_SRTP_DECRYPT_FAILED                   STATUS_SRTP_BASE + 0x00000001
#define STATUS_SRTP_ENCRYPT_FAILED                   STATUS_SRTP_BASE + 0x00000002
#define STATUS_SRTP_TRANSMIT_SESSION_CREATION_FAILED STATUS_SRTP_BASE + 0x00000003
#define STATUS_SRTP_RECEIVE_SESSION_CREATION_FAILED  STATUS_SRTP_BASE + 0x00000004
#define STATUS_SRTP_INIT_FAILED                      STATUS_SRTP_BASE + 0x00000005
#define STATUS_SRTP_NOT_READY_YET                    STATUS_SRTP_BASE + 0x00000006
#define STATUS_SRTCP_DECRYPT_FAILED                  STATUS_SRTP_BASE + 0x00000007
#define STATUS_SRTCP_ENCRYPT_FAILED                  STATUS_SRTP_BASE + 0x00000008
/*!@} */

/////////////////////////////////////////////////////
/// RTP related status codes
/////////////////////////////////////////////////////

/*! \addtogroup RTPStatusCodes
 * WEBRTC RTP related codes. Values are derived from STATUS_RTP_BASE (0x5c000000)
 *  @{
 */
#define STATUS_RTP_BASE                   STATUS_SRTP_BASE + 0x01000000
#define STATUS_RTP_INPUT_PACKET_TOO_SMALL STATUS_RTP_BASE + 0x00000001
#define STATUS_RTP_INPUT_MTU_TOO_SMALL    STATUS_RTP_BASE + 0x00000002
#define STATUS_RTP_INVALID_NALU           STATUS_RTP_BASE + 0x00000003
#define STATUS_RTP_INVALID_EXTENSION_LEN  STATUS_RTP_BASE + 0x00000004
#define STATUS_RTP_NULL_ARG               STATUS_RTP_BASE + 0x00000005
#define STATUS_RTP_BUFFER_TOO_SMALL       STATUS_RTP_BASE + 0x00000006
#define STATUS_RTP_NOT_ENOUGH_MEMORY      STATUS_RTP_BASE + 0x00000007
/*!@} */

/////////////////////////////////////////////////////
/// Signaling related status codes
/////////////////////////////////////////////////////

/*! \addtogroup SignalingStatusCodes
 * WEBRTC Signaling related codes. Values are derived from STATUS_SIGNALING_BASE (0x5d000000)
 *  @{
 */
#define STATUS_SIGNALING_BASE                                      STATUS_RTP_BASE + 0x01000000
#define STATUS_SIGNALING_INVALID_READY_STATE                       STATUS_SIGNALING_BASE + 0x00000001
#define STATUS_SIGNALING_GET_TOKEN_CALL_FAILED                     STATUS_SIGNALING_BASE + 0x00000002
#define STATUS_SIGNALING_DESCRIBE_CALL_FAILED                      STATUS_SIGNALING_BASE + 0x00000003
#define STATUS_SIGNALING_CREATE_CALL_FAILED                        STATUS_SIGNALING_BASE + 0x00000004
#define STATUS_SIGNALING_GET_ENDPOINT_CALL_FAILED                  STATUS_SIGNALING_BASE + 0x00000005
#define STATUS_SIGNALING_GET_ICE_CONFIG_CALL_FAILED                STATUS_SIGNALING_BASE + 0x00000006
#define STATUS_SIGNALING_READY_CALLBACK_FAILED                     STATUS_SIGNALING_BASE + 0x00000007
#define STATUS_SIGNALING_CONNECT_CALL_FAILED                       STATUS_SIGNALING_BASE + 0x00000008
#define STATUS_SIGNALING_CONNECTED_CALLBACK_FAILED                 STATUS_SIGNALING_BASE + 0x00000009
#define STATUS_SIGNALING_INVALID_CHANNEL_INFO_VERSION              STATUS_SIGNALING_BASE + 0x0000000A
#define STATUS_SIGNALING_INVALID_SIGNALING_CALLBACKS_VERSION       STATUS_SIGNALING_BASE + 0x0000000B
#define STATUS_SIGNALING_INVALID_CHANNEL_NAME_LENGTH               STATUS_SIGNALING_BASE + 0x0000000C
#define STATUS_SIGNALING_INVALID_CHANNEL_ARN_LENGTH                STATUS_SIGNALING_BASE + 0x0000000D
#define STATUS_SIGNALING_INVALID_REGION_LENGTH                     STATUS_SIGNALING_BASE + 0x0000000E
#define STATUS_SIGNALING_INVALID_CPL_LENGTH                        STATUS_SIGNALING_BASE + 0x0000000F
#define STATUS_SIGNALING_INVALID_CERTIFICATE_PATH_LENGTH           STATUS_SIGNALING_BASE + 0x00000010
#define STATUS_SIGNALING_INVALID_AGENT_POSTFIX_LENGTH              STATUS_SIGNALING_BASE + 0x00000011
#define STATUS_SIGNALING_INVALID_AGENT_LENGTH                      STATUS_SIGNALING_BASE + 0x00000012
#define STATUS_SIGNALING_INVALID_KMS_KEY_LENGTH                    STATUS_SIGNALING_BASE + 0x00000013
#define STATUS_SIGNALING_LWS_CREATE_CONTEXT_FAILED                 STATUS_SIGNALING_BASE + 0x00000014
#define STATUS_SIGNALING_LWS_CLIENT_CONNECT_FAILED                 STATUS_SIGNALING_BASE + 0x00000015
#define STATUS_SIGNALING_CHANNEL_BEING_DELETED                     STATUS_SIGNALING_BASE + 0x00000016
#define STATUS_SIGNALING_INVALID_CLIENT_INFO_VERSION               STATUS_SIGNALING_BASE + 0x00000017
#define STATUS_SIGNALING_INVALID_CLIENT_INFO_CLIENT_LENGTH         STATUS_SIGNALING_BASE + 0x00000018
#define STATUS_SIGNALING_MAX_ICE_CONFIG_COUNT                      STATUS_SIGNALING_BASE + 0x00000019
#define STATUS_SIGNALING_MAX_ICE_URI_COUNT                         STATUS_SIGNALING_BASE + 0x0000001A
#define STATUS_SIGNALING_MAX_ICE_URI_LEN                           STATUS_SIGNALING_BASE + 0x0000001B
#define STATUS_SIGNALING_NO_CONFIG_SPECIFIED                       STATUS_SIGNALING_BASE + 0x0000001C
#define STATUS_SIGNALING_INVALID_ICE_CONFIG_INFO_VERSION           STATUS_SIGNALING_BASE + 0x0000001D
#define STATUS_SIGNALING_NO_CONFIG_URI_SPECIFIED                   STATUS_SIGNALING_BASE + 0x0000001E
#define STATUS_SIGNALING_NO_ARN_RETURNED_ON_CREATE                 STATUS_SIGNALING_BASE + 0x0000001F
#define STATUS_SIGNALING_MISSING_ENDPOINTS_IN_GET_ENDPOINT         STATUS_SIGNALING_BASE + 0x00000020
#define STATUS_SIGNALING_INVALID_MESSAGE_TYPE                      STATUS_SIGNALING_BASE + 0x00000021
#define STATUS_SIGNALING_INVALID_SIGNALING_MESSAGE_VERSION         STATUS_SIGNALING_BASE + 0x00000022
#define STATUS_SIGNALING_NO_PEER_CLIENT_ID_IN_MESSAGE              STATUS_SIGNALING_BASE + 0x00000023
#define STATUS_SIGNALING_MESSAGE_DELIVERY_FAILED                   STATUS_SIGNALING_BASE + 0x00000024
#define STATUS_SIGNALING_MAX_MESSAGE_LEN_AFTER_ENCODING            STATUS_SIGNALING_BASE + 0x00000025
#define STATUS_SIGNALING_RECEIVE_BINARY_DATA_NOT_SUPPORTED         STATUS_SIGNALING_BASE + 0x00000026
#define STATUS_SIGNALING_RECEIVE_EMPTY_DATA_NOT_SUPPORTED          STATUS_SIGNALING_BASE + 0x00000027
#define STATUS_SIGNALING_RECEIVED_MESSAGE_LARGER_THAN_MAX_DATA_LEN STATUS_SIGNALING_BASE + 0x00000028
#define STATUS_SIGNALING_INVALID_PAYLOAD_LEN_IN_MESSAGE            STATUS_SIGNALING_BASE + 0x00000029
#define STATUS_SIGNALING_NO_PAYLOAD_IN_MESSAGE                     STATUS_SIGNALING_BASE + 0x0000002A
#define STATUS_SIGNALING_DUPLICATE_MESSAGE_BEING_SENT              STATUS_SIGNALING_BASE + 0x0000002B
#define STATUS_SIGNALING_ICE_TTL_LESS_THAN_GRACE_PERIOD            STATUS_SIGNALING_BASE + 0x0000002C
#define STATUS_SIGNALING_DISCONNECTED_CALLBACK_FAILED              STATUS_SIGNALING_BASE + 0x0000002D
#define STATUS_SIGNALING_INVALID_MESSAGE_TTL_VALUE                 STATUS_SIGNALING_BASE + 0x0000002E
#define STATUS_SIGNALING_ICE_CONFIG_REFRESH_FAILED                 STATUS_SIGNALING_BASE + 0x0000002F
#define STATUS_SIGNALING_RECONNECT_FAILED                          STATUS_SIGNALING_BASE + 0x00000030
#define STATUS_SIGNALING_DELETE_CALL_FAILED                        STATUS_SIGNALING_BASE + 0x00000031
#define STATUS_SIGNALING_INVALID_METRICS_VERSION                   STATUS_SIGNALING_BASE + 0x00000032
#define STATUS_SIGNALING_INVALID_ICE_CONFIG_COUNT                  STATUS_SIGNALING_BASE + 0x00000033
#define STATUS_SIGNALING_NULL_ARG                                  STATUS_SIGNALING_BASE + 0x00000034
#define STATUS_SIGNALING_CREATE_THREAD_FAILED                      STATUS_SIGNALING_BASE + 0x00000035
#define STATUS_SIGNALING_CREATE_MSGQ_FAILED                        STATUS_SIGNALING_BASE + 0x00000036
#define STATUS_SIGNALING_DISPATCH_FAILED                           STATUS_SIGNALING_BASE + 0x00000037
#define STATUS_SIGNALING_LWS_CALL_FAILED                           STATUS_SIGNALING_BASE + 0x00000038
#define STATUS_SIGNALING_LWS_SERVICE_FAILED                        STATUS_SIGNALING_BASE + 0x00000039

/*!@} */

/////////////////////////////////////////////////////
/// Peer connection related status codes
/////////////////////////////////////////////////////

/*! \addtogroup PeerConnectionStatusCodes
 * WEBRTC STUN related codes. Values are derived from STATUS_PEERCONNECTION_BASE
 * (0x5e000000)
 *  @{
 */
#define STATUS_PEERCONNECTION_BASE                                     STATUS_SIGNALING_BASE + 0x01000000
#define STATUS_PEERCONNECTION_CREATE_ANSWER_WITHOUT_REMOTE_DESCRIPTION STATUS_PEERCONNECTION_BASE + 0x00000001
#define STATUS_PEERCONNECTION_CODEC_INVALID                            STATUS_PEERCONNECTION_BASE + 0x00000002
#define STATUS_PEERCONNECTION_CODEC_MAX_EXCEEDED                       STATUS_PEERCONNECTION_BASE + 0x00000003
#define STATUS_PEERCONNECTION_NO_CONNECTION                            STATUS_PEERCONNECTION_BASE + 0x00000004
#define STATUS_PEERCONNECTION_NO_SCTP_SESSION                          STATUS_PEERCONNECTION_BASE + 0x00000005
#define STATUS_PEERCONNECTION_NO_ON_MESSAGE                            STATUS_PEERCONNECTION_BASE + 0x00000006
#define STATUS_PEERCONNECTION_INVALID_TIMER                            STATUS_PEERCONNECTION_BASE + 0x00000007
/*!@} */

/////////////////////////////////////////////////////
/// SCTP related status codes
/////////////////////////////////////////////////////

/*! \addtogroup SCTPStatusCodes
 * WEBRTC SCTP related codes. Values are derived from STATUS_STUN_BASE (0x5f000000)
 *  @{
 */
#define STATUS_SCTP_BASE                    STATUS_PEERCONNECTION_BASE + 0x01000000
#define STATUS_SCTP_SESSION_SETUP_FAILED    STATUS_SCTP_BASE + 0x00000001
#define STATUS_SCTP_INVALID_DCEP_PACKET     STATUS_SCTP_BASE + 0x00000002
#define STATUS_SCTP_SO_NON_BLOCKING_FAILED  STATUS_SCTP_BASE + 0x00000003
#define STATUS_SCTP_SO_CREATE_FAILED        STATUS_SCTP_BASE + 0x00000004
#define STATUS_SCTP_SO_BIND_FAILED          STATUS_SCTP_BASE + 0x00000005
#define STATUS_SCTP_SO_CONNECT_FAILED       STATUS_SCTP_BASE + 0x00000006
#define STATUS_SCTP_SO_LINGER_FAILED        STATUS_SCTP_BASE + 0x00000007
#define STATUS_SCTP_SO_NODELAY_FAILED       STATUS_SCTP_BASE + 0x00000008
#define STATUS_SCTP_EVENT_FAILED            STATUS_SCTP_BASE + 0x00000009
#define STATUS_SCTP_INITMSG_FAILED          STATUS_SCTP_BASE + 0x0000000A
#define STATUS_SCTP_PEER_ADDR_PARAMS_FAILED STATUS_SCTP_BASE + 0x0000000B

/*!@} */

/////////////////////////////////////////////////////
/// RTCP related status codes
/////////////////////////////////////////////////////

/*! \addtogroup RTCPStatusCodes
 * WEBRTC RTCP related codes. Values are derived from STATUS_RTCP_BASE (0x60000000)
 *  @{
 */
#define STATUS_RTCP_BASE                         STATUS_SCTP_BASE + 0x01000000
#define STATUS_RTCP_INPUT_PACKET_TOO_SMALL       STATUS_RTCP_BASE + 0x00000001
#define STATUS_RTCP_INPUT_PACKET_INVALID_VERSION STATUS_RTCP_BASE + 0x00000002
#define STATUS_RTCP_INPUT_PACKET_LEN_MISMATCH    STATUS_RTCP_BASE + 0x00000003
#define STATUS_RTCP_INPUT_NACK_LIST_INVALID      STATUS_RTCP_BASE + 0x00000004
#define STATUS_RTCP_INPUT_SSRC_INVALID           STATUS_RTCP_BASE + 0x00000005
#define STATUS_RTCP_INPUT_PARTIAL_PACKET         STATUS_RTCP_BASE + 0x00000006
#define STATUS_RTCP_INPUT_REMB_TOO_SMALL         STATUS_RTCP_BASE + 0x00000007
#define STATUS_RTCP_INPUT_REMB_INVALID           STATUS_RTCP_BASE + 0x00000008
#define STATUS_RTCP_NULL_ARG                     STATUS_RTCP_BASE + 0x00000009
/*!@} */

/////////////////////////////////////////////////////
/// Rolling buffer related status codes
/////////////////////////////////////////////////////

/*! \addtogroup RollingBufferStatusCodes
 * WEBRTC Rolling Buffer related codes. Values are derived from STATUS_ROLLING_BUFFER_BASE
 * (0x61000000)
 *  @{
 */
#define STATUS_ROLLING_BUFFER_BASE         STATUS_RTCP_BASE + 0x01000000
#define STATUS_ROLLING_BUFFER_NOT_IN_RANGE STATUS_ROLLING_BUFFER_BASE + 0x00000001
/*!@} */

/////////////////////////////////////////////////////
/// AWSSignerV4 related status codes
/////////////////////////////////////////////////////

/*! \addtogroup AWSSignerV4StatusCodes
 * WEBRTC AWSSignerV4 related codes. Values are derived from STATUS_AWS_SIGNER_BASE (0x62000000)
 *  @{
 */
#define STATUS_AWS_SIGNER_BASE                   STATUS_ROLLING_BUFFER_BASE + 0x01000000
#define STATUS_AWS_SIGNER_FAIL_TO_CALCULATE_HASH STATUS_AWS_SIGNER_BASE + 0x00000001
/*!@} */

/////////////////////////////////////////////////////
/// Json related status codes
/////////////////////////////////////////////////////

/*! \addtogroup JsonStatusCodes
 * WEBRTC json related codes. Values are derived from STATUS_JSON_BASE (0x63000000)
 *  @{
 */
#define STATUS_JSON_BASE        STATUS_AWS_SIGNER_BASE + 0x01000000
#define STATUS_JSON_PARSE_ERROR STATUS_JSON_BASE + 0x00000001
/*!@} */

/////////////////////////////////////////////////////
/// http related status codes
/////////////////////////////////////////////////////

/*! \addtogroup httpStatusCodes
 * WEBRTC http related codes. Values are derived from STATUS_JSON_BASE (0x64000000)
 *  @{
 */
#define STATUS_HTTP_BASE                      STATUS_JSON_BASE + 0x01000000
#define STATUS_HTTP_RES_NOT_FOUND_ERROR       STATUS_HTTP_BASE + 0x00000001
#define STATUS_HTTP_REST_EXCEPTION_ERROR      STATUS_HTTP_BASE + 0x00000002
#define STATUS_HTTP_REST_NOT_AUTHORIZED_ERROR STATUS_HTTP_BASE + 0x00000003
#define STATUS_HTTP_REST_UNKNOWN_ERROR        STATUS_HTTP_BASE + 0x00000004
/*!@} */

/////////////////////////////////////////////////////
/// wss related status codes
/////////////////////////////////////////////////////

/*! \addtogroup wssStatusCodes
 * WEBRTC wss related codes. Values are derived from STATUS_JSON_BASE (0x65000000)
 *  @{
 */
#define STATUS_WSS_BASE                      STATUS_HTTP_BASE + 0x01000000
#define STATUS_WSS_CLIENT_SEND_FAILED        STATUS_WSS_BASE + 0x00000001
#define STATUS_WSS_CLIENT_RECV_FAILED        STATUS_WSS_BASE + 0x00000001
#define STATUS_WSS_UPGRADE_CONNECTION_ERROR  STATUS_WSS_BASE + 0x00000002
#define STATUS_WSS_UPGRADE_PROTOCOL_ERROR    STATUS_WSS_BASE + 0x00000003
#define STATUS_WSS_ACCEPT_KEY_ERROR          STATUS_WSS_BASE + 0x00000004
#define STATUS_WSS_GENERATE_CLIENT_KEY_ERROR STATUS_WSS_BASE + 0x00000005
#define STATUS_WSS_GENERATE_ACCEPT_KEY_ERROR STATUS_WSS_BASE + 0x00000005
#define STATUS_WSS_VALIDATE_ACCEPT_KEY_ERROR STATUS_WSS_BASE + 0x00000006
#define STATUS_WSS_GENERATE_RANDOM_NUM_ERROR STATUS_WSS_BASE + 0x00000007
/*!@} */

#ifdef __cplusplus
}
#endif
#endif /* __KINESIS_VIDEO_WEBRTC_CLIENT_ERROR__ */
